[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "NLPPlus"
version = "2.0.0"

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
