[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "NLPPlus"
version = "1.1.0"
authors = [
    {name = "David De Hilster", email="ddh@visualtext.org"}
]

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
