name: Test

on:
  workflow_dispatch:
    
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install
      run: pip install -ve .
    - name: test
      run: python -m unittest discover -s tests

